### ISSUE TITLE
How do I apply filters to an HTML-GL element

### ISSUE THREAD

**Issue by viziionary** [PixelsCommander/HTML-GL#60]
Sorry if this seems like a silly question, but from reading the Repo Readme, I see how to use `<html-gl>` to cause the library to render the elements with WebGL, but I'm trying to figure out how to apply filters. Could someone explain how that is done, for example if I wanted to apply a filter to a whole page the way you show in examples? I looked into those page's resources but wasnt able to figure it out.

**Comment by PixelsCommander** [comment]
You may apply filters via html tag attribute ```<html-gl effects="riples">``` unfortunately ripples is only filter supported by attribute at the moment. We are working together with Pixi author in order to get more.

Also you may add as it is done in http://pixelscommander.com/polygon/htmlgl/demo/filters.html via Pixi.filters let me know if you have any problems with that.
