### ISSUE TITLE
I need an explanation

### ISSUE THREAD

**Issue by lluxx** [PixelsCommander/HTML-GL#77]
I am using pure javascript. So, how would I create image element with this? I am using document.createElement('img'); most of the time, so how can I turn it html-gl element?

Another thing, does this library only allows css transforms, or it is working with for example element.style.width, element.style.display etc? Can we access current position, size and other things with it?

**Comment by PixelsCommander** [comment]
https://github.com/PixelsCommander/HTML-GL/blob/master/src/gl-element.js#L291

Use HTMLGL.GLElement.createFromNode(node)

Not sure what do you mean. It reacts on DOM changes based on Mutation Observer. Here is a sepc on this https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver

It means that changing element style properties does not trigger rerendering. Attribute or DOM content should be changed.

Also it consumes node.styleGL.transform in the way you would expect it to use node.style.transform. Which is the most performant way of changing coordinates.

Not clear what do you mean by accessing other things. You may use updateTexture on node to rerender its content in order to fit current size, styling and children.

**Comment by PixelsCommander** [comment]
If you have more questions do not hesitate to give me a shot in skype lp_funky
